### ISSUE TITLE
Case sensitivity

### ISSUE THREAD

**Issue by msageryd** [paseto-standard/paseto-spec#39]
I stumbled upon PASETO while researching a shorter form of token than JWT. We had two needs:
- shorter tokens
- case insensitivity

It seems as PASETO won't fulfill any of those. 
**Question:** Is is possible to generate PASETO tokens with only small caps?

The reason is that we need to use tokens in query strings for sending out links in emails. Some Outlook/Exchange spam filters will convert all urls in emails to small caps, which will destroy JWT tokens as well as PASETO I think.

**Comment by aidantwoods** [comment]
(Omitting some thoughts about email filters that mangle content being the problem here).

I think your goals are incompatible. Either you can have case insensitive tokens, or you can have shorter tokens. Case insensitivity means you have approximately half as many characters to represent data, and so the encoded data will need to be longer. 

You could solve for case insensitivity by (e.g.) hex encoding a token. This will make it longer, but will make it recoverable under casing transformations.

**Comment by msageryd** [comment]
Thanks, that's what I thought. Your omitted email filter thoughts are probably valid. I'm furious, but I cannot do anything about it, so I have to adapt.

I don't need completely stateless tokens. I only need an expiration timestamp and a resonably secure sugnature so I can minimize database hits. The actual information is linked to each token in a database anyway. I will move forward with my home cooked tokens for this purpose.
